ДЗ 2
Cow-a-banga/2024-2-VK-EDU-Frontend-D-Chiruhin pull request #2
Opened 2024-09-24 15:24 UTC by Cow-a-banga

# Домашнее задание №2

Прошу @martinkomitsky, @haseprogram, @kgrechin проверить его.

Что было сделано:
* Добавлена стилизация чата
* Добавлена логика сохранения сообщений в localStorage и загрузки оттуда 
* Проект задеплоен по ссылке https://cow-a-banga.github.io/2024-2-VK-EDU-Frontend-D-Chiruhin/

2024-09-29 11:10 UTC, kgrechin requested changes

2024-09-29 11:10 UTC, kgrechin commented on simple-chat/src/index.js
> +scrollToTheBottom();
круто было бы если мы бы использовали LS только для того чтобы первый раз считать данные и после анмаунта сохранить, а так работали с локальным стейтом

2024-09-30 03:35 UTC, kgrechin requested changes

2024-09-30 03:35 UTC, kgrechin commented on simple-chat/src/index.css
> +html {
<img width="417" alt="Снимок экрана 2024-09-30 в 06 33 58" src="https://github.com/user-attachments/assets/a19adbb8-a693-40fe-be44-6a20ea0ad00c">

чет на мобилке не очень))

2024-09-30 10:18 UTC, Cow-a-banga commented on simple-chat/src/index.js
> +scrollToTheBottom();
готово

2024-09-30 10:18 UTC, Cow-a-banga commented on simple-chat/src/index.css
> +html {
поправил
![изображение](https://github.com/user-attachments/assets/917de7ac-176f-4525-b66a-55b9ca87c025)

2024-09-30 10:19 UTC, Cow-a-banga commented on simple-chat/src/index.js
> +scrollToTheBottom();
готово

2024-10-02 05:59 UTC, kgrechin approved these changes
@HaseProgram, @martinkomitsky, от меня аппрув

2024-10-02 21:00 UTC, HaseProgram approved these changes
Огонь, 12!

2024-10-02 21:01 UTC, merged