ДЗ 3
Cow-a-banga/2024-2-VK-EDU-Frontend-D-Chiruhin pull request #3
Opened 2024-10-03 09:25 UTC by Cow-a-banga

# Домашнее задание №3

Прошу @martinkomitsky, @haseprogram, @kgrechin проверить его.

Что было сделано:
* Добавлена страница с чатами с возможностью перейти в чат и обратно
* Файлы css/js разделены на модули
* function заменены на стрелочные

Деплой по адресу: https://cow-a-banga.github.io/2024-2-VK-EDU-Frontend-D-Chiruhin/

2024-10-04 06:54 UTC, kgrechin requested changes
@Cow-a-banga, впринципе только 1 замечание, в остальном все соответсвует дз)

2024-10-04 06:54 UTC, kgrechin commented on simple-chat/src/index/index.html
> +                <a class="chat" href="./chat/chat.html">
добавить отображение сообщений собеседника

2024-10-07 10:28 UTC, Cow-a-banga commented on simple-chat/src/index/index.html
> +                <a class="chat" href="./chat/chat.html">
Привет, не совсем понял что именно нужно: добавить сообщения собеседника в чате и/или отображение последнего сообщения в списке чатов (учитывая что ты выделил), поэтому добавил и то, и то

2024-10-08 05:31 UTC, kgrechin approved these changes
@Cow-a-banga, класс, единственное в следующих дз надо будет пофиксить скролл, чтобы он был не на всю страницу, а только у блока с сообщениями

2024-10-08 05:32 UTC, kgrechin commented
@HaseProgram, @martinkomitsky от меня аппрув

2024-10-09 07:55 UTC, HaseProgram approved these changes
12!

2024-10-09 07:55 UTC, merged