ДЗ 6
Cow-a-banga/2024-2-VK-EDU-Frontend-D-Chiruhin pull request #6
Opened 2024-10-24 12:55 UTC by Cow-a-banga

# Домашнее задание №6

Прошу @martinkomitsky, @haseprogram, @kgrechin проверить его.

Что было сделано:
* Добавлен роутинг
* Добавлена страница профиля
* Изменён UI для десктопной версии
Деплой: https://cow-a-banga.github.io/2024-2-VK-EDU-Frontend-D-Chiruhin/

2024-10-26 08:11 UTC, kgrechin requested changes
@Cow-a-banga, продублирую из прошлого дз:

Структура и декомпозиция на компоненты:
components - папка с тупыми компонентами, в которых не будет логики работы с апи/сторами, LS и тд, примеры компонентов - Button, Header, Form, Card, Layout (можно отдельную папку layouts создать) и тд

modules - папка с компонентам в которых будет логика работы с апи/сторами и тд, пример структуры:
modules/chat/ - ChatList, ChatForm...
modules/messages/ - MessageList, MessageItem...

нужно пофиксить

2024-10-31 06:21 UTC, kgrechin commented
@Cow-a-banga, напоминаю о фиксах)

2024-11-05 12:08 UTC, Cow-a-banga commented
@kgrechin Прошу прощения что долго тянул. 
Изменил структуру папок и удалил ChatList, так как он пока особо сильно не нужен, а понадобится +- когда до redux дойдём.
Сейчас освободился и буду догонять по задачкам.

2024-11-07 07:16 UTC, kgrechin commented
<img width="1679" alt="Снимок экрана 2024-11-07 в 10 16 31" src="https://github.com/user-attachments/assets/e9910de9-6344-43cc-8bba-4de9dfa6e58f">

@Cow-a-banga, привет) упал деплой( надо пофиксить

2024-11-07 07:17 UTC, kgrechin requested changes
@Cow-a-banga, по коду глазами прошелся - все ок, надо поправить билд на gh pages

2024-11-07 11:19 UTC, kgrechin approved these changes

2024-11-07 11:20 UTC, kgrechin commented
12!

2024-11-07 11:20 UTC, merged